fix(workspaceBox) show thumbs when dual screens
pop-os/cosmic-workspaces pull request #88
Opened 2024-05-14 20:44 UTC by danilopinotti

Hello!

This is my proposal to fix the following bug:
- When we use two screens and set "Placement of the Workspace Picker" as "Along the **right** side", the second screen, when we open the workspace view, does not show any window.
- Using  "Placement of the Workspace Picker" as "Along the **left** side", it works correctly.

Should fix:
- https://github.com/pop-os/cosmic-workspaces/issues/87
- https://github.com/pop-os/gnome-shell/issues/102
- https://github.com/pop-os/pop/issues/2528

2024-05-14 21:40 UTC, mmstick approved these changes

2024-05-15 17:07 UTC, leviport requested changes
With this patch installed, I'm not seeing the workspace picker appear when set to either side of the screen. I tested with a 4K primary display and a 2K secondary display. I also set the 4K to 2K resolution and arranged it to the left, above, and to the right of the primary display. None of these configurations I tried made the picker appear on my secondary display.

2024-05-17 09:17 UTC, SoulRaven commented
same here, i have try the patch and not working.
i have 3 monitors setup and this problem is 3-4 days on my system
Left or Right, the picker is not present on any of the secondary monitors, only on the primary one.

2024-05-22 13:51 UTC, durka commented
unfortunately doesn't fix #87

2024-05-22 14:17 UTC, danilopinotti commented
Hello!
Sorry, I made a mistake when I said that fixes "workspace picker" bug. This PR fixes the windows miniatures in secondary screen.

# Before
![Screenshot from 2024-05-22 11-16-49](https://github.com/pop-os/cosmic-workspaces/assets/11338999/532269c8-63ee-4861-b782-83fb9869c922)

# After
![Screenshot from 2024-05-22 11-13-08](https://github.com/pop-os/cosmic-workspaces/assets/11338999/48788837-dd7f-4c5b-935d-45ece3a09faa)

2024-05-22 14:44 UTC, leviport approved these changes
Ah I see now, sorry for the misunderstanding. This PR definitely does bring back the mini window previews on secondary screens. I thought the intention was to bring back workspace picker, so that's what I thought didn't work. Bringing back the mini previews is an improvement in behavior.

2024-05-23 00:03 UTC, jackpot51 approved these changes

2024-05-23 00:03 UTC, merged